spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/ROADMAP?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    url: jdbc:mariadb://61.245.226.237:3306/ROADMAP?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      
server : 
  port : 8000
  
mybatis : 
  mapper-locations : com/roadmap/roadmapservice/dao/*.xml