spring:
  datasource:
    url: jdbc:mariadb://193.123.247.150:3360/ROADMAP
    driver-class-name: org.mariadb.jdbc.Driver
    username: roadmap
    password: roadmap
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
      
server : 
  port : 8000
  
mybatis : 
  mapper-locations : mapper/**/*.xml